# Generated by Django 2.2 on 2020-03-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20200301_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='bruker', max_length=30),
        ),
    ]
