# Generated by Django 2.2 on 2020-03-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200318_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='bruker', max_length=30),
        ),
    ]
