# Generated by Django 2.2 on 2020-03-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200301_1221'),
        ('users', '0002_auto_20200301_1313'),
    ]

    operations = [
    ]
