# Generated by Django 2.2 on 2020-02-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200221_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_vote',
            field=models.IntegerField(default=0),
        ),
    ]
